# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 427f9fca3567f680dff18236a1d60e4b0fb6f8cbbf823a55204bb800fda0d416562a810aa2967f5f28c8cf82b8529c631695c42ee09361910aad16c9f3fdde3b

test:
  secret_key_base: 45d8ca5fe8fd0a7c5381cc6ffccbb20b1fa48a1dce127332b73da5a804a9ecd10109bfe7736746c705572fdcc4b42df558e86f095fbaaaf5abed2f9fe7a5e40e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
